# Attacking with a weapon adds its enchantment to the weapon's to-hit and damage value. e.g. +1 dagger: +1 to-hit, +1 damage
WeaponData = {
    'orcish dagger': {'Type': 'dagger', 'Cost': 4, 'Weight': 10, 'Damage_small': 2, 'Damage_large': 2, 'Damage': 2},
    'orcish daggers': {'Type': 'dagger', 'Cost': 4, 'Weight': 10, 'Damage_small': 2, 'Damage_large': 2, 'Damage': 2},
    'dagger': {'Type': 'dagger', 'Cost': 4, 'Weight': 10, 'Damage_small': 2.5, 'Damage_large': 2, 'Damage': 2.25},
    'daggers': {'Type': 'dagger', 'Cost': 4, 'Weight': 10, 'Damage_small': 2.5, 'Damage_large': 2, 'Damage': 2.25},
    'silver dagger': {'Type': 'dagger', 'Cost': 40, 'Weight': 12, 'Damage_small': 2.5, 'Damage_large': 2, 'Damage': 2.25},
    'silver daggers': {'Type': 'dagger', 'Cost': 40, 'Weight': 12, 'Damage_small': 2.5, 'Damage_large': 2, 'Damage': 2.25},
    'athame': {'Type': 'dagger', 'Cost': 4, 'Weight': 10, 'Damage_small': 2.5, 'Damage_large': 2, 'Damage': 2.25},
    'elven dagger': {'Type': 'dagger', 'Cost': 4, 'Weight': 10, 'Damage_small': 3, 'Damage_large': 2, 'Damage': 2.5},
    'elven daggers': {'Type': 'dagger', 'Cost': 4, 'Weight': 10, 'Damage_small': 3, 'Damage_large': 2, 'Damage': 2.5},
    'worm tooth': {'Type': 'knife', 'Cost': 2, 'Weight': 20, 'Damage_small': 1.5, 'Damage_large': 1.5, 'Damage': 1.5},
    'knife': {'Type': 'knife', 'Cost': 4, 'Weight': 5, 'Damage_small': 2, 'Damage_large': 1.5, 'Damage': 1.75},
    'shito': {'Type': 'knife', 'Cost': 4, 'Weight': 5, 'Damage_small': 2, 'Damage_large': 1.5, 'Damage': 1.75}, # samurai
    'stiletto': {'Type': 'knife', 'Cost': 4, 'Weight': 5, 'Damage_small': 2, 'Damage_large': 1.5, 'Damage': 1.75},
    'scalpel': {'Type': 'knife', 'Cost': 4, 'Weight': 5, 'Damage_small': 2, 'Damage_large': 2, 'Damage': 2},
    'crysknife': {'Type': 'knife', 'Cost': 100, 'Weight': 20, 'Damage_small': 5.5, 'Damage_large': 5.5, 'Damage': 5.5},
    'axe': {'Type': 'axe', 'Cost': 8, 'Weight': 60, 'Damage_small': 3.5, 'Damage_large': 2.5, 'Damage': 3},
    'battle-axe': {'Type': 'axe', 'Cost': 40, 'Weight': 120, 'Damage_small': 7, 'Damage_large': 6, 'Damage': 6.5},
    'pick-axe': {'Type': 'pick-axe', 'Cost': 50, 'Weight': 100, 'Damage_small': 3.5, 'Damage_large': 2, 'Damage': 2.75},
    'dwarvish mattock': {'Type': 'pick-axe', 'Cost': 50, 'Weight': 120, 'Damage_small': 6.5, 'Damage_large': 11.5, 'Damage': 9},
    'orcish short sword': {'Type': 'short sword', 'Cost': 10, 'Weight': 30, 'Damage_small': 3, 'Damage_large': 4.5, 'Damage': 3.75},
    'short sword': {'Type': 'short sword', 'Cost': 10, 'Weight': 30, 'Damage_small': 3.5, 'Damage_large': 4.5, 'Damage': 4},
    'wakizashi': {'Type': 'short sword', 'Cost': 10, 'Weight': 30, 'Damage_small': 3.5, 'Damage_large': 4.5, 'Damage': 4}, # samurai
    'dwarvish short sword': {'Type': 'short sword', 'Cost': 10, 'Weight': 30, 'Damage_small': 4, 'Damage_large': 4.5, 'Damage': 4.25},
    'elven short sword': {'Type': 'short sword', 'Cost': 10, 'Weight': 30, 'Damage_small': 4.5, 'Damage_large': 4.5, 'Damage': 4.5},
    'broadsword': {'Type': 'broadsword', 'Cost': 10, 'Weight': 70, 'Damage_small': 5, 'Damage_large': 4.5, 'Damage': 4.75},
    'ninja-to': {'Type': 'broadsword', 'Cost': 10, 'Weight': 70, 'Damage_small': 5, 'Damage_large': 4.5, 'Damage': 4.75}, # samurai
    'runesword': {'Type': 'broadsword', 'Cost': 300, 'Weight': 40, 'Damage_small': 5, 'Damage_large': 4.5, 'Damage': 4.75},
    'elven broadsword': {'Type': 'broadsword', 'Cost': 10, 'Weight': 70, 'Damage_small': 6, 'Damage_large': 4.5, 'Damage': 5.25},
    'long sword': {'Type': 'long sword', 'Cost': 15, 'Weight': 40, 'Damage_small': 4.5, 'Damage_large': 6.5, 'Damage': 5.5},
    'katana': {'Type': 'long sword', 'Cost': 80, 'Weight': 40, 'Damage_small': 5.5, 'Damage_large': 6.5, 'Damage': 6},
    'two-handed sword': {'Type': 'two-handed sword', 'Cost': 50, 'Weight': 150, 'Damage_small': 6.5, 'Damage_large': 10.5, 'Damage': 8.5},
    'tsurugi': {'Type': 'two-handed sword', 'Cost': 500, 'Weight': 60, 'Damage_small': 8.5, 'Damage_large': 11.5, 'Damage': 10},
    'scimitar': {'Type': 'scimitar', 'Cost': 15, 'Weight': 40, 'Damage_small': 4.5, 'Damage_large': 4.5, 'Damage': 4.5},
    'silver saber': {'Type': 'saber', 'Cost': 75, 'Weight': 40, 'Damage_small': 4.5, 'Damage_large': 4.5, 'Damage': 4.5},
    'club': {'Type': 'club', 'Cost': 3, 'Weight': 30, 'Damage_small': 3.5, 'Damage_large': 2, 'Damage': 2.75},
    'aklys': {'Type': 'club', 'Cost': 4, 'Weight': 15, 'Damage_small': 3.5, 'Damage_large': 2, 'Damage': 2.75},
    'mace': {'Type': 'mace', 'Cost': 5, 'Weight': 30, 'Damage_small': 4.5, 'Damage_large': 3.5, 'Damage': 4},
    'morning star': {'Type': 'morning star', 'Cost': 10, 'Weight': 120, 'Damage_small': 5, 'Damage_large': 4.5, 'Damage': 4.75},
    'flail': {'Type': 'flail', 'Cost': 4, 'Weight': 15, 'Damage_small': 4.5, 'Damage_large': 5, 'Damage': 4.75},
    'nunchaku': {'Type': 'flail', 'Cost': 4, 'Weight': 15, 'Damage_small': 4.5, 'Damage_large': 5, 'Damage': 4.75}, # samurai
    'grappling hook': {'Type': 'flail', 'Cost': 50, 'Weight': 30, 'Damage_small': 1.5, 'Damage_large': 3.5, 'Damage': 2.5},
    'war hammer': {'Type': 'hammer', 'Cost': 5, 'Weight': 50, 'Damage_small': 3.5, 'Damage_large': 2.5, 'Damage': 3},
    'quarterstaff': {'Type': 'quarterstaff', 'Cost': 5, 'Weight': 40, 'Damage_small': 3.5, 'Damage_large': 3.5, 'Damage': 3.5},
    'partisan': {'Type': 'polearms', 'Cost': 10, 'Weight': 80, 'Damage_small': 3.5, 'Damage_large': 4.5, 'Damage': 4},
    'fauchard': {'Type': 'polearms', 'Cost': 5, 'Weight': 60, 'Damage_small': 3.5, 'Damage_large': 4.5, 'Damage': 4},
    'glaive': {'Type': 'polearms', 'Cost': 6, 'Weight': 75, 'Damage_small': 3.5, 'Damage_large': 5.5, 'Damage': 4.5},
    'naginata': {'Type': 'polearms', 'Cost': 6, 'Weight': 75, 'Damage_small': 3.5, 'Damage_large': 5.5, 'Damage': 4.5}, # samurai
    'bec-de-corbin': {'Type': 'polearms', 'Cost': 8, 'Weight': 100, 'Damage_small': 4.5, 'Damage_large': 3.5, 'Damage': 4},
    'bec de corbin': {'Type': 'polearms', 'Cost': 8, 'Weight': 100, 'Damage_small': 4.5, 'Damage_large': 3.5, 'Damage': 4},
    'spetum': {'Type': 'polearms', 'Cost': 5, 'Weight': 50, 'Damage_small': 4.5, 'Damage_large': 7, 'Damage': 5.75},
    'lucern hammer': {'Type': 'polearms', 'Cost': 7, 'Weight': 150, 'Damage_small': 5, 'Damage_large': 3.5, 'Damage': 4.25},
    'guisarme': {'Type': 'polearms', 'Cost': 5, 'Weight': 80, 'Damage_small': 5, 'Damage_large': 4.5, 'Damage': 4.75},
    'ranseur': {'Type': 'polearms', 'Cost': 6, 'Weight': 50, 'Damage_small': 5, 'Damage_large': 5, 'Damage': 5},
    'voulge': {'Type': 'polearms', 'Cost': 5, 'Weight': 125, 'Damage_small': 5, 'Damage_large': 5, 'Damage': 5},
    'bill-guisarme': {'Type': 'polearms', 'Cost': 7, 'Weight': 120, 'Damage_small': 5, 'Damage_large': 5.5, 'Damage': 5.25},
    'bill guisarme': {'Type': 'polearms', 'Cost': 7, 'Weight': 120, 'Damage_small': 5, 'Damage_large': 5.5, 'Damage': 5.25},
    'bardiche': {'Type': 'polearms', 'Cost': 7, 'Weight': 120, 'Damage_small': 5, 'Damage_large': 7.5, 'Damage': 6.25},
    'halberd': {'Type': 'polearms', 'Cost': 10, 'Weight': 150, 'Damage_small': 5.5, 'Damage_large': 7, 'Damage': 6.25},
    'orcish spear': {'Type': 'spear', 'Cost': 3, 'Weight': 30, 'Damage_small': 3, 'Damage_large': 4.5, 'Damage': 3.75},
    'spear': {'Type': 'spear', 'Cost': 3, 'Weight': 30, 'Damage_small': 3.5, 'Damage_large': 4.5, 'Damage': 4},
    'silver spear': {'Type': 'spear', 'Cost': 40, 'Weight': 36, 'Damage_small': 3.5, 'Damage_large': 4.5, 'Damage': 4},
    'elven spear': {'Type': 'spear', 'Cost': 3, 'Weight': 30, 'Damage_small': 4, 'Damage_large': 4.5, 'Damage': 4.25},
    'dwarvish spear': {'Type': 'spear', 'Cost': 3, 'Weight': 35, 'Damage_small': 4.5, 'Damage_large': 4.5, 'Damage': 4.5},
    'javelin': {'Type': 'spear', 'Cost': 3, 'Weight': 20, 'Damage_small': 3.5, 'Damage_large': 3.5, 'Damage': 3.5},
    'trident': {'Type': 'trident', 'Cost': 5, 'Weight': 25, 'Damage_small': 4.5, 'Damage_large': 7.5, 'Damage': 6},
    'lance': {'Type': 'lance', 'Cost': 10, 'Weight': 180, 'Damage_small': 3.5, 'Damage_large': 4.5, 'Damage': 4},
    'orcish bow': {'Type': 'bow', 'Cost': 60, 'Weight': 30, 'Damage_small': 1.5, 'Damage_large': 1.5, 'Damage': 1.5},
    'orcish arrow': {'Type': 'bow', 'Cost': 2, 'Weight': 1, 'Damage_small': 3, 'Damage_large': 3.5, 'Damage': 3.25},
    'orcish arrows': {'Type': 'bow', 'Cost': 2, 'Weight': 1, 'Damage_small': 3, 'Damage_large': 3.5, 'Damage': 3.25},
    'bow': {'Type': 'bow', 'Cost': 60, 'Weight': 30, 'Damage_small': 1.5, 'Damage_large': 1.5, 'Damage': 1.5},
    'arrow': {'Type': 'bow', 'Cost': 2, 'Weight': 1, 'Damage_small': 3.5, 'Damage_large': 3.5, 'Damage': 3.5},
    'arrows': {'Type': 'bow', 'Cost': 2, 'Weight': 1, 'Damage_small': 3.5, 'Damage_large': 3.5, 'Damage': 3.5},
    'elven bow': {'Type': 'bow', 'Cost': 60, 'Weight': 30, 'Damage_small': 1.5, 'Damage_large': 1.5, 'Damage': 1.5},
    'elven arrow': {'Type': 'bow', 'Cost': 2, 'Weight': 1, 'Damage_small': 4, 'Damage_large': 3.5, 'Damage': 3.75},
    'elven arrows': {'Type': 'bow', 'Cost': 2, 'Weight': 1, 'Damage_small': 4, 'Damage_large': 3.5, 'Damage': 3.75},
    'yumi': {'Type': 'bow', 'Cost': 60, 'Weight': 30, 'Damage_small': 1.5, 'Damage_large': 1.5, 'Damage': 1.5},
    'ya': {'Type': 'bow', 'Cost': 4, 'Weight': 1, 'Damage_small': 4, 'Damage_large': 4, 'Damage': 4},
    'silver arrow': {'Type': 'bow', 'Cost': 5, 'Weight': 1, 'Damage_small': 3.5, 'Damage_large': 3.5, 'Damage': 3.5},
    'silver arrows': {'Type': 'bow', 'Cost': 5, 'Weight': 1, 'Damage_small': 3.5, 'Damage_large': 3.5, 'Damage': 3.5},
    'sling': {'Type': 'sling', 'Cost': 20, 'Weight': 3, 'Damage_small': 1.5, 'Damage_large': 1.5, 'Damage': 1.5},
    'flint stone': {'Type': 'sling', 'Cost': 1, 'Weight': 10, 'Damage_small': 3.5, 'Damage_large': 3.5, 'Damage': 3.5},
    'crossbow': {'Type': 'crossbow', 'Cost': 40, 'Weight': 50, 'Damage_small': 1.5, 'Damage_large': 1.5, 'Damage': 1.5},
    'crossbow bolt': {'Type': 'crossbow', 'Cost': 2, 'Weight': 1, 'Damage_small': 3.5, 'Damage_large': 4.5, 'Damage': 4},
    'dart': {'Type': 'dart', 'Cost': 2, 'Weight': 1, 'Damage_small': 2, 'Damage_large': 1.5, 'Damage': 1.75},
    'darts': {'Type': 'dart', 'Cost': 2, 'Weight': 1, 'Damage_small': 2, 'Damage_large': 1.5, 'Damage': 1.75},
    'shuriken': {'Type': 'shuriken', 'Cost': 5, 'Weight': 1, 'Damage_small': 4.5, 'Damage_large': 3.5, 'Damage': 4},
    'boomerang': {'Type': 'boomerang', 'Cost': 20, 'Weight': 5, 'Damage_small': 5, 'Damage_large': 5, 'Damage': 5},
    'bullwhip': {'Type': 'whip', 'Cost': 4, 'Weight': 20, 'Damage_small': 1.5, 'Damage_large': 1, 'Damage': 1.25},
    'rubber hose': {'Type': 'whip', 'Cost': 3, 'Weight': 20, 'Damage_small': 2.5, 'Damage_large': 2, 'Damage': 2.25},
    'unicorn horn': {'Type': 'unicorn horn', 'Cost': 100, 'Weight': 20, 'Damage_small': 6.5, 'Damage_large': 6.5, 'Damage': 6.5},
}
# print (WeaponData.get('dagger').get('Damage'))
