train_dir: ???
experiment: ???

model:
    agent: dmlab_multitask_agent
    encoder:
        encoder_subtype: resnet_impala_large
        encoder_pooling: stride
    core:
        core_type: trxl
        n_layer: 6
        hidden_size: 512
    use_half_policy_worker: True

optim:
    type: adam
    learning_rate: 0.0001
    batch_size: 1536
    rollout: 96
    max_grad_norm: 2.5

learner:
    exploration_loss_coeff: 0.003
    psychlab_gamma: 0.7
    use_decoder: True
    reconstruction_loss_coeff: 0.01

env:
    action_set: extended_action_set_large
